### PR TITLE
Make st3 compatible

### PR DESCRIPTION
**Pull request by Starli0n**
Hi,

Could you please review my change ?

I make it so that the plugin is compatible with both `st2` and `st3`.

Thanks

### CODE REVIEW

**Comment by titoBouzout** [comment]
Thanks!

**Comment by Starli0n** [comment]
Come on, you are fast!!
Thanks!

**Comment by Starli0n** [comment]
Have you ever think about integrating you package to [Package Control](https://packagecontrol.io) ?

(I could help if necessary)

**Comment by titoBouzout** [comment]
I just sit here and got a notification of your request, that distracted me enough to take a quick look, I looked, then merge was very quick, good. Now, If I had to add the version thingy, then I need to clone/merge your request on my local version then tag, then push, for what? for nothing. I dont want to deal with version numbers, I prefer to do anything else. Later, have fun, thanks again

**Comment by Starli0n** [comment]
1. To be referenced in Package Control
2. To ease the installation of users like me that use your package
3. Because it is cool :-)

But it is your choice, I respect it

**Pull request merged**
