### PR TITLE
Add [ ] to enable wiki-style links

### PR DESCRIPTION
**Pull request by xHN35RQ**
Add ability to open files between [ ] to enable wiki-style links for compatibility with Notational Velocity / nvALT or to create your own personal wiki within Sublime Text.

Thanks for making such a great plugin!

### CODE REVIEW

**Comment by titoBouzout** [comment]
Cool, thank you :)

**Comment by xHN35RQ** [comment]
No problem, let me know if you need anything from me to merge this. Thanks.

**Comment by titoBouzout** [comment]
I just forget to push merge lol

**Comment by xHN35RQ** [comment]
cool thanks again.

**Pull request merged**
